#!/bin/bash
# Aggregate learnings from completed Gang evaluations
# Reads postmortem.md files across all evaluations and produces insights
# Usage: aggregate-learnings.sh [gang_root]
set -uo pipefail

GANG_ROOT="${1:-.gang}"
LEARNINGS_DIR="$GANG_ROOT/learnings"
OUTPUT_FILE="$LEARNINGS_DIR/aggregated-$(date +%Y%m%d).md"

mkdir -p "$LEARNINGS_DIR"

echo "Gang Learnings Aggregation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Find all postmortem files
POSTMORTEMS=()
while IFS= read -r f; do
  POSTMORTEMS+=("$f")
done < <(find "$GANG_ROOT" -name "postmortem.md" -type f 2>/dev/null)

if [[ ${#POSTMORTEMS[@]} -eq 0 ]]; then
  echo "No postmortem files found. Complete some evaluations first."
  exit 0
fi

echo "Found ${#POSTMORTEMS[@]} postmortem(s)"
echo ""

# Count verdicts
GO_COUNT=0
NOGO_COUNT=0
CONDITIONAL_COUNT=0

for pm in "${POSTMORTEMS[@]}"; do
  VERDICT=$(grep -i "Verdict:" "$pm" 2>/dev/null | head -1 || true)
  case "$VERDICT" in
    *GO*NO*|*NO*GO*) NOGO_COUNT=$((NOGO_COUNT + 1)) ;;
    *CONDITIONAL*) CONDITIONAL_COUNT=$((CONDITIONAL_COUNT + 1)) ;;
    *GO*) GO_COUNT=$((GO_COUNT + 1)) ;;
  esac
done

# Count completed check-ins (any checkbox is checked)
CHECKINS=0
for pm in "${POSTMORTEMS[@]}"; do
  if grep -q "\[x\]" "$pm" 2>/dev/null; then
    CHECKINS=$((CHECKINS + 1))
  fi
done

# Extract wrong assumptions
WRONG_ASSUMPTIONS=""
for pm in "${POSTMORTEMS[@]}"; do
  DIR=$(dirname "$pm")
  if [[ -f "$DIR/assumptions.json" ]]; then
    # Count assumptions that were validated as wrong
    WRONG=$(jq '[.[] | select(.validated == true and .validation_result != null and (.validation_result | test("wrong|incorrect|false|invalid"; "i")))] | length' "$DIR/assumptions.json" 2>/dev/null || echo 0)
    if [[ "$WRONG" -gt 0 ]]; then
      CATEGORIES=$(jq -r '[.[] | select(.validated == true and .validation_result != null and (.validation_result | test("wrong|incorrect|false|invalid"; "i"))) | .category] | group_by(.) | map({category: .[0], count: length}) | .[] | "\(.category): \(.count)"' "$DIR/assumptions.json" 2>/dev/null || true)
      WRONG_ASSUMPTIONS="$WRONG_ASSUMPTIONS\n$CATEGORIES"
    fi
  fi
done

# Write aggregation report
cat > "$OUTPUT_FILE" << EOF
# Gang Learnings — Aggregated $(date +%Y-%m-%d)

## Overview
- **Total evaluations:** ${#POSTMORTEMS[@]}
- **Verdicts:** GO: $GO_COUNT | CONDITIONAL-GO: $CONDITIONAL_COUNT | NO-GO: $NOGO_COUNT
- **Check-ins completed:** $CHECKINS / ${#POSTMORTEMS[@]}

## Verdict Accuracy
$(if [[ "$CHECKINS" -gt 0 ]]; then
  echo "Based on $CHECKINS completed check-ins:"
  for pm in "${POSTMORTEMS[@]}"; do
    if grep -q "\[x\]" "$pm" 2>/dev/null; then
      EVAL=$(basename "$(dirname "$pm")")
      CORRECT=$(grep -c "\[x\] Yes" "$pm" 2>/dev/null || echo 0)
      WRONG_VERDICT=$(grep -c "\[x\] No" "$pm" 2>/dev/null || echo 0)
      echo "- **$EVAL:** $(if [[ "$CORRECT" -gt 0 ]]; then echo "Correct"; elif [[ "$WRONG_VERDICT" -gt 0 ]]; then echo "Wrong"; else echo "Pending"; fi)"
    fi
  done
else
  echo "No check-ins completed yet. Fill in postmortem.md files after 3 months."
fi)

## Assumption Categories That Failed Most
$(if [[ -n "$WRONG_ASSUMPTIONS" ]]; then
  echo -e "$WRONG_ASSUMPTIONS" | sort | uniq -c | sort -rn | head -10
else
  echo "No validated assumption failures recorded yet."
fi)

## Recommendations
- Review assumption categories that fail frequently and add extra scrutiny in future evaluations
- If verdicts are frequently wrong, consider adjusting scoring rubric thresholds
- Use these learnings to calibrate future Gang evaluations

---
*Generated by aggregate-learnings.sh on $(date)*
EOF

echo "Aggregation written to: $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "  Evaluations: ${#POSTMORTEMS[@]}"
echo "  Verdicts: GO=$GO_COUNT CONDITIONAL=$CONDITIONAL_COUNT NO-GO=$NOGO_COUNT"
echo "  Check-ins: $CHECKINS completed"
